spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/fkBackEnd
    username: oldaim
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: cZlsmdpaLksSAdsdmdaskjndasdas1j234214lasdasdasSnadaklsnd242adsadndkanskdskahfbj3123122k
  access_valid_time: 1200000
  refresh_valid_time: 1209600033

upload:
    path: "/Users/kimdonggyun/Desktop/bootpicture/"

gmail:
  credential_path: "/Users/kimdonggyun/Desktop/credit/credentials.json"
  admin_user_id: "dgk0911@gmail.com"
  token_directory_path: "tokens"

