spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: oldaim
    password:
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret: cZlsmdpaLksSAdsdmdaskjndasdas1j234214lasdasdasSnadaklsnd242adsadndkanskdskahfbj3123122k
  access_valid_time: 1200000
  refresh_valid_time: 1209600033

upload:
    path: "/var/lib/docker/volumes/fkproject-volume/_data/fkprojectpicture/"

gmail:
  credential_path: "/Users/kimdonggyun/Desktop/credit/credentials.json"
  admin_user_id: "dgk0911@gmail.com"
  token_directory_path: "tokens"

logging:
    level:
       org:
          springframework:
            web:
             filter:
                CommonsRequestLoggingFilter: DEBUG